# Site settings
title: Unredacted Word - ZC6 / ZN6 86
email: enquiries@unredacted-word.pub
baseurl: "/86"
url: "https://unredacted-word.pub/86"
timezone: "America/New_York"
description: "Subaru BRZ and Toyota 86 motorsports parts."


# Build settings
permalink: pretty
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - LICENSE
  - README.md

